### ISSUE TITLE
مشکل ریلیز ۰.۰.۷ 

### ISSUE THREAD

**Issue by aziz** [font-store/font-nika#1]
فقط یک فایل پی ان جی داخل زیپ هست.

**Comment by aziz** [comment]
!ی‍‍‍ادت نره

```
git tag 0.0.9
git push --tags
```

**Comment by aziz** [comment]
بیلد اسکریپتت رو هم پابلیش کن. 
حتما یه کدی داری که کانفیگ رو میخونه و تو دیست فولدر پابلیش می‌کنه دیگه نه؟‌

**Comment by zoghal** [comment]
تگ گذاری مگر بیشتر برای نسخه های قابل انتشار نیست؟ از این جهت من تگ نزدم.

> بیلد اسکریپتت رو هم پابلیش کن.
> حتما یه کدی داری که کانفیگ رو میخونه و تو دیست فولدر پابلیش می‌کنه دیگه نه؟‌

والا اسکریپت نیست. در کل یک پروداکت هست. یک سیستم اتوماسیون فونت و که از یکسری روند و ابزار وابسته تشکیل شده به نوعی که از طراحی تا ساخت فونت رو مکانیزه و اتوماتیک میکنه.
فعلا هم تحت توسعه هست.
اول قرار بود این سیستم تحت کلود و برای پروژه خانه فونت باشه. اما داستان همکاری با طراحان حروف  و بازی که سر ما در آوردن باعث شد در دو نسخه دیگر توسعه بدم. الان هم دارم روی نسخه تک کاربره اون کار میکنم. که باید کراس پلتفورم باشه که فقط ویندوزش داره تکمیل میشه و نیاز هست برای تحت لینوکس و مک یک پلاگین برای inkscape بنویسیم.

تو این سیستم فقط نیاز به svg گلیف هست. گلیف های که تو فولدر svg هست.بقیه کارها تا ۹۰٪ اتوماتیک انجام میشه.
فعلا دارم ۲۰ فونت رو باهاش انجام میدم تا تکمیل بشه. و بشه به عنوان یک پکیج منتشرش کرد.
متاسفانه مشکلات سر راه هم کم نیست. اما تمام سعی‌ام این هست تا ۷ ماه آینده آماده بشه. چون بعید میدونم بیشتر از ۷ ماه بتونم دوام بیارم.:)

**Comment by aziz** [comment]
یه نکته دیگه در مورد اسکرین‌شات های صفحه رید می این ریپو است. 
صالح جان ۱۰ تا فونت مختلف تو این اسکرین‌شات ها به کار رفته مردم اصلا نمیفهمند که کدوم فونت الان اونیه که قراره باشه! 
به نظرم همشونو حذف کن. تو اسکرین‌شات‌ها فقط از نیکا استفاده کن نه هیچ قلم دیگه‌ای

**Comment by zoghal** [comment]
حق دارید. داریم روش کار میکنم. . متاسفانه از نظر گرافیک من کمی بی ذوق هستم.
البته این تصاویر بیشتر برای انتشار بیهنس هست.
در اصل چندتای اول در همه فونت ها تکرار میشه. 
دارم روش کار میکنم.
