### ISSUE TITLE
شکل میم چسبان آخر

### ISSUE THREAD

**Issue by aziz** [font-store/font-nika#2]
این تیزی سر میم قدری عجیبه. بهتر نیست عادی و صاف باشه؟
<img width="227" alt="screen shot 2016-03-27 at 6 27 48 pm" src="https://cloud.githubusercontent.com/assets/3202/14066464/2be25058-f44a-11e5-8f7e-9448ef355457.png">

**Comment by zoghal** [comment]
در نسخه ۰.۰.۷ تیزی‌ها بر طرف شده. تو نسخه ۰.۱.۰ هم ضخامت‌ها و دورها کنترل و بازنگری شدند. چند ساعتی دیگر آپلود میشه.

**Comment by zoghal** [comment]
تغییر دادم این فرم آخر میم رو. میبندم این ایشو اگر موردی بود لطفا مجدد نظرتون رو بگید.
