### ISSUE TITLE
اندازه نقاط

### ISSUE THREAD

**Issue by aziz** [font-store/font-nika#3]
به نظرم قلم آزاد از نظر شکل و اندازه نقاط بهتر کار کرده
<img width="227" src="https://cloud.githubusercontent.com/assets/3202/14066476/91c4afba-f44a-11e5-852d-c9cb497409ff.png" align="right">
<img width="260" src="https://cloud.githubusercontent.com/assets/3202/14066477/93def378-f44a-11e5-966d-cbd8436372df.png" align="right">

**Comment by zoghal** [comment]
پی فونت  چون برای سایز ریز بیشتر استفاده میشه. حروفش خیلی کشیدگی داره. میشه نقاط رو بزرگتر گرفت. اما تو نیکا تموم سایز‌ها مد نظرم هست. نقاط درشت تر روی یک سری حروف مثل «ببینم» تمام فضا رو میگیرند و شدیدا سیاهی میزنه.
البته فعلا نمیتونم قطعی نظر بدم. میزارم تو تسک‌ها برای چک کردن و تست این موضوع

**Comment by aziz** [comment]
به نظرم حرفت منطقیه. یکی از معضلات رایج طراحی قلم همین جا دادن همه نقاط در کلمات پرنقطه است شاید کم کردن اندکی از اندازه نقطه هزینه کمی است برای جلوگیری از هزینه‌های بزرگتر جایگزاری نقاط

**Comment by rastikerdar** [comment]
نمونه:

![screenshot from 2016-03-28 21-30-29](https://cloud.githubusercontent.com/assets/3116038/14083710/5980fd9c-f52c-11e5-970a-f1db6a98a775.png)

**Comment by zoghal** [comment]
نقاط بزرگتر شدند، و فرم حروف با نقاط هماهنگ شدند.
