### ISSUE TITLE
 مشکل همیشگی کرنینگ رزژو با سایر حروف

### ISSUE THREAD

**Issue by aziz** [font-store/font-nika#4]
<img width="181" alt="screen shot 2016-03-27 at 7 33 57 pm" src="https://cloud.githubusercontent.com/assets/3202/14066773/5c29b6da-f453-11e5-93d5-cdde630b5c4a.png">
<img width="137" alt="screen shot 2016-03-27 at 7 34 06 pm" src="https://cloud.githubusercontent.com/assets/3202/14066774/5d514820-f453-11e5-8c11-7396d3a0d210.png">

**Comment by zoghal** [comment]
در نسخه جدید رفع شده. بزودی پوش میشه
