### ISSUE TITLE
نسخه‌ بولد و نازک قلم

### ISSUE THREAD

**Issue by aziz** [font-store/font-nika#5]
تبریک می‌گم و خسته نباشی. 
خیلی خوب و حرفه‌ای شده مخصوصا اون نمایش آنلاین رو خیلی خوشم اومد. 
من یه کمک ناقابلی برات کنار گذاشتم برای قدردانی از این کار نمی‌دونم چطوری به دستت برسونم. اگر خودت راه حلی داری برام ایمیل بزن و گرنه باید صبر کنی تا یکی از فک و فامیل بیاد ایران و برات بیاره.

**Comment by zoghal** [comment]
> تبریک می‌گم و خسته نباشی. 
>  خیلی خوب و حرفه‌ای شده مخصوصا اون نمایش آنلاین رو خیلی خوشم اومد. 

همه درد و بلاهایی که سر این فونت فارسی کشیدم یک طرف. این دوخط یک طرف دیگه لذت داره وقتی استاد آدم به شاگردش آفرین و صد آفرین بگه. خستگیم رو در آوردی..
عزیزجان فراموش نکن ما شاگرد خودتیم، اگر راهنمایی‌های شما تو زمان موببل تایپ نبود ما الان مثل پویا سلیمی داشتیم با وردپرس بازی می‌کردیم :دی . نصایح شما رو شنیدیم و انجامش دادیم. هرچه که هست، رو از شما و دیگر اساتیدم دارم.

> نسخه‌ بولد و نازک قلم

راستش فعلا قرار نیست روی وزن‌های دیگه کاری انجام بشه. به دو دلیل:

۱- پیرامون فونت اصلا جو خوبی وجود ندارد و نیاز به فرهنگ سازی دارد. و خیلی وقته روی این موضوع دارم کار میکنم. کلی هم سرو صدا کردم. ارائه و تکمیل این فونت و سایر فونت‌های دیگه اصلا به صلاح نیست. متاسفانه ورود رستگار به داستان فونت فارسی اساسا مشکلات زیادی رو بوجود آورد واسم. این عزیز با خودداری کردن از بیان زحماتش و سختی‌های کار باعث شد که یک عده سو استفاده کنند و کارهای رستگار رو برزنند تو سر من و بدتر از همه مسلم ابراهیمی یا همون fontiran.com.
این کار واقعا فرسایشی هست و باید شکل و روش درست به خودش رو بگیره وگرنه با چند فونت برای مدتی یک نیاز رو ماست مالی می‌کنیم ولی اصل موضوع سر جایش هست.
 من برنامه نویسم و قرار بود این برنامه رو با همکاری طراحان حروف انجام بدیم که متاسفانه دورمون زدند البته الظاهر. نیکا و فربد رو هم برای این طراحی کردم که ابتدا می‌بایست بت طراحی و اون داستان رمز آلود بودن هنر طراحان حروف رو میشکستم تا راه رو برای افراد جدید باز کنم. وگرنه این کار کار گروهی هست و دولوپ بخشی از روند توسعه فونت.

۲- من زمانی که فهمیدم این بندگان خدا خودشون هم سواد لازم رو ندارند و فقط سیاه نمایی میکنند تا خودشون رو بزرگ کنند، نشستم از صفر تا صد طراحی  تایپ فیس تا پیاده سازی فونت رو تجزیه و تحلیل کردم. و نتایج رو مستند . خوب فعلا نیکا حاصل همین تحقیق هست.
یکی از اهداف من رساندن فونت‌های فارسی به یک استاندارد استیبل بود که تحقیقش با موفقیت انجام شد و مونده پیاده سازی و تکمیل جزییات. مثل مباحثی که مطرح کردم. در گروه.
یکی از موارد هم همین وزن کشی هست.این کار رو من الان بصورت اتوماتیک روی حروف اعمال میکنم. منتها هنوز به پکیج فونت ساز اضافه نشده. و کمی زمان میبره. به جرعت هر فونتی که تولید بشه توسط RFB از لحاظ زخمات در وزن ها هیچ تفاوتی دیده نمیشه. و همه در یک سطح قرار دارند. البته اگر کشش لازم رو داشته باشند.
الان نیکا در این استایل تا ۶ وزن و مونولاینش در ۹ وزن جوابگو هست. و باید به اینقطه برسه.

متاسفانه اگر جو رو سامان ندیم، و جلوی این طراحان حروف وای نسیم اینها به کارهاشون ادامه میدند و به اسم هویت بصری سر یک عده رو کلاه میگذارند و جامعه رو تشنه نگه میدارند.

داستان داریم ما :)) فرصت کردید هماهنگ کن تا براتون تعریف کنم چی گذشته و چی کردند به من این هنرمندان فریحخته.

>  من یه کمک ناقابلی برات کنار گذاشتم برای قدردانی از این کار نمی‌دونم چطوری به دستت برسونم. اگر خودت راه حلی داری برام ایمیل بزن و گرنه باید صبر کنی تا یکی از فک و فامیل بیاد ایران و برات بیاره.

اوه اوه دمت جیز نه همون دلاری بهتره الان به دیجیتال اوشن بدهکارم شدم. وی پی اس خانه فونت رو خاموش کردند. الان ایمیل میزنم.
مررررررررررسی

**Comment by rastikerdar** [comment]
چرا اطلاع رسانی نمی کنید انتشارشو آقا صالح؟

**Comment by zoghal** [comment]
صابر جان تمامی ۲۰ فونت‌ هرکدامشون  یک ابزار برای اطلاع رسانی و فرهنگ سازی هست.
دارم روی صفحات پرزنت و پروفایل فونت ها کار میکنم. نیکا یک فونت کلیدی و مهمی برای من هست. [اینجا](http://font-store.github.io/font-nika/) رو بخون، کمی از داستان نیکا  رو برای تست گذاشتم.
قبلا هم متذکر شدم و بالا هم توضیحاتی پیرامون برنامه هام دادم. سر این قضیه بود که اصلا می خواستم باهات صحبت کنم. که مایل نبودی و این حرفا.
نیکا رو اگر خدا بخواد روز پدر رسما منتشر میشه. و بقیه به پشت سر اون. فعلا پنج تا دیگه داره آماده میشه.

**Comment by rastikerdar** [comment]
آخه می خواستم معرفیش کنم گفتم شاید هنوز تا قبل از انتشار رسمیش راضی نباشید!
البته در مورد برخی گلیف هاش یه چند تا نکته به ذهنم رسید که به نظرم اومد فعلا دارین تغییر میدین و مایل نباشید.

**Comment by zoghal** [comment]
زیاد فرقی به حالم نداره.  چون اون معرفی شما کمی با معرفی من فرق داره. من تو شبکه های اجتماعی فالوئر زیادی دارم چه اکانت‌های شخصیم چه اکانت های خانه فونت. اون شماره ۶ رو هم جو گیر بازی شدم :))

تغییرات که آره زیاد داشته. شما بگو نظرت رو بابا. فونت ماله من که نیست. مال نیکاست. اون راضیه فقط فونت میخواد وروجک، حالا  من کی باشم که راضی نباشم.
بگو بزن بکش آزادی دادش

**Comment by rastikerdar** [comment]
من می‌خواستم در جاهای مختلف به سهم و توان خودم تشویق کنم برای حمایت مالی اما خب می‌فرمایید فرقی به حالتون نداره.
به هر حال برای شما آرزوی موفقیت دارم.

**Comment by zoghal** [comment]
لطف شما ثابت شده هست. منظور از من از«فرق» این بود که با برنامه‌هام تداخلی نداره و مشکلی خاصی نیست.(بابت اون راضی نباشید که گفتی)
سپاس برادر
