### ISSUE TITLE
شکل عجیب حرف ه

### ISSUE THREAD

**Issue by sijad** [font-store/font-nika#7]
بنده در کار فونت‌ هیچگونه سوادی ندارم
عذرخواهی می‌کنم
ولی فکر می‌کنم حرف `ه` به صورت عمودی کمی کشیده هست و کمی شبیه عدد ۵ شده

**Comment by sijad** [comment]
البته منظور بنده از عدد ۵، عدد ۵ عربی هست

**Comment by zoghal** [comment]
درود بر شما
واقعیت اینه که باسواد‌هاش همون بی سواد حال زمان هستند:دی پس باهاشون کاری نداریم.
میرسیم به خودمون که بی سوادیم و این فونت هم برای بی سواد‌هاست. با سواد ها فونت‌هاشون رو کاری دیگه میکی کنند.. بگذریم.
.
و نکته ای که اشاره کردید بسیار درست و صحیح هست. فراموش کرده بودم ویرایشش کنم.
گذاشتم تو لیست تودو تو تا چند روزه دیگه نسخه جدید رو منتشر میکنم.
سپاس

**Comment by zoghal** [comment]
درود تغییرات جدیدی در نسخه 0.1.2 اعمال شد. از جمله این مورد.
ایشو رو میبندم . در صورتی که باز مشکلی داشتید لطفا بازش کنید.
شاد و پیروز باشید.

**Comment by sijad** [comment]
با توجه به https://github.com/font-store/font-nika/commit/78e0004d4aff4dd8f5d41713a150f320a5075c0c تصاویر پیش‌نمایش تغییر کردند ولی بنده هرچقدر توجه کردم نتونستم تغییر ضاهری متوجه بشم

**Comment by zoghal** [comment]
بهترین راه مقایسه فولدر svg هست
نسخه ۰.۱.۲ : https://github.com/font-store/font-nika/blob/master/svg/_.he8.isol.svg
نسخه ۰.۱.۱ : https://github.com/font-store/font-nika/blob/v0.1.1/svg/_.he8.isol.svg
