### ISSUE TITLE
تغییر عکس‌های پیشنمایش برای نسخه v0.1.2

### ISSUE THREAD

**Issue by sijad** [font-store/font-nika#8]
بنده هرچه با ابزارهای مختلف امتحان کردم نتونستم تفاوتی در عکس‌های پیشنمایش جدید مشاهده کنم
فکر می‌کنم نیاز هست عکس‌ها بروز شوند
https://github.com/font-store/font-nika/tree/master/docs

**Comment by zoghal** [comment]
خوب راستش زیاد جدی نگیرید این تصاویر رو چون موقتی هستند. و داره دموی اصلی آماده میشه.
http://font-store.github.io/font-nika/
فعلا روی چند ایده و سیستم دریافت حمایت فوکوس کردم. تا چند روز دیگه تموم میشه. و تصاویر  کنار گذاشته میشه و معیار مقایسه همون فرم svg خواهد بود.
اگر نظری یا پیشنهادی داشته باشید. شدیدا استقبال میکنم. چون کمی کج سلیقه هستم.
