### ISSUE TITLE
استفاده در سویفت ؟

### ISSUE THREAD

**Issue by J-Arji** [font-store/font-nika#9]
سلام 
آیا میشه این فونت را در سویفت هم استفاده کرد ؟
در صورت امکان ممنون میشم راهنمای کنید :+1:

**Comment by zoghal** [comment]
یکی آرزوهام اینه که بتونم به یکی از پلتفرم‌های اپل دسترسی داشته باشم.
اما خوب حتی توانایی مجازی سازی رو هم ندارم.
پس تجربه ای در این مورد ندارم. اما دلیلی هم وجود نداره که نشه.
فکر میکنم تو گوگل سرچ کنید پیدا میکنید راهکار لازم رو

**Comment by J-Arji** [comment]
ممنونم از شما :)
جسارتن یه توصیه می کنم بهتون از همون دور نگاش کنید بهتره 
با سختگیری های دست و پاگیرش کفر آدم رو در میاره

**Comment by J-Arji** [comment]
البته اعتراف میکنم دوس داشتنی هست  :dart:
